import {basePath} from '@/sanity/env'

/** The engraved rosette, a static SVG generated by scripts/rosette-svg.mjs (kept out of the HTML, it is 200 KB of path data). */
export function Rosette({size = 360, className}: {size?: number; className?: string}) {
  // eslint-disable-next-line @next/next/no-img-element
  return <img src={`${basePath}/rosette.svg`} width={size} height={size} alt="" aria-hidden="true" className={className} decoding="async" />
}
